### ISSUE TITLE
Unable to compile for Web

### ISSUE THREAD

**Issue by jvnphotography** [abdulaziz-mohammed/whiteboardkit#3] opened 2020-04-28 17:15 UTC
Hi!
Trying to use this package - did a simple new app (web-based), added to pubspec, ran flutter pub get and imported. Nothing else.
On trying to run I get this:
Performing hot restart...
Syncing files to device Chrome...

Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/whiteboardkit-0.1.8/lib/gesture_whiteboard_controller.dart:63:15: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
        ..add(Point.fromOffset(position));
              ^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/whiteboardkit-0.1.8/lib/gesture_whiteboard_controller.dart:77:39: Error: 'Point' is imported from both 'dart:math' and 'dart:ui'.
      this.draw.lines.last.points.add(Point.fromOffset(secondPoint));
                                      ^^^^^
What might the problem be?

**Comment by abdulaziz-mohammed** [comment] 2020-05-10 10:35
it was caused by unnecessary usage of "dart:ui" package, now fixed on "0.1.9". sorry for the delay
Thanks for reporting

**Closed by abdulaziz-mohammed** 2020-05-10 10:35 UTC

**Comment by jvnphotography** [comment] 2020-05-13 12:42
No worries, thanks for the reply, fix and update. And, of course, for contributing. Have a good one!
